# boot.cmd - U-Boot main boot script for Orange Pi RV2
#
# Modified from boot.cmd in the Orange Pi official U-Boot repository:
# https://github.com/orangepi-xunlong/OrangePi_Build
#
# This script is compiled to boot.scr and loaded by U-Boot at startup.
# It provides a boot menu allowing selection between:
#   - Default Orange Pi Linux boot
#   - xv6-riscv kernel boot
#   - U-Boot console
#
# The script sources either default.scr or xv6.scr based on menu selection.
# Place compiled .scr files in the /boot partition.
#
# Compile with: mkimage -C none -A riscv -T script -d boot.cmd boot.scr
#
# DO NOT EDIT THIS FILE
#
# Please edit /boot/orangepiEnv.txt to set supported parameters
#

setenv load_addr "0x9000000"
setenv load_addr1 "0x9010000"
setenv load_addr2 "0x9020000"
setenv overlay_error "false"
# default values
setenv verbosity "1"
setenv console "both"
setenv bootlogo "true"
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv earlycon "on"
setenv bootdelay 5

# Setup boot menu entries
setenv bootmenu_delay 10

if test -e ${devtype} ${devnum} ${prefix}default.scr; then
	load ${devtype} ${devnum} ${load_addr1} ${prefix}default.scr
	setenv bootmenu_0 "Default boot (Orange Pi)=source ${load_addr1}"
fi

if test -e ${devtype} ${devnum} ${prefix}xv6.scr; then
	load ${devtype} ${devnum} ${load_addr2} ${prefix}xv6.scr
	setenv bootmenu_1 "Boot xv6-riscv kernel=source ${load_addr2}"
fi

if test -e ${devtype} ${devnum} ${prefix}xv6-tftp.scr; then
	load ${devtype} ${devnum} 0x9030000 ${prefix}xv6-tftp.scr
	setenv bootmenu_2 "Boot xv6-riscv (TFTP)=source 0x9030000"
	setenv bootmenu_3 "U-Boot console=echo Dropping to U-Boot console..."
else
	setenv bootmenu_2 "U-Boot console=echo Dropping to U-Boot console..."
fi

# Show boot menu
bootmenu


echo "Fall back to default boot sequence"
echo "Boot script loaded from ${devtype} ${devnum}"

#if test -e ${devtype} ${devnum} ${prefix}orangepiEnv.txt; then
	load ${devtype} ${devnum} ${load_addr} ${prefix}orangepiEnv.txt
	env import -t ${load_addr} ${filesize}
#fi

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=ttyS0,115200 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlycon=sbi ${consoleargs}"; fi
if test "${bootlogo}" = "true"; then setenv consoleargs "bootsplash.bootfile=bootsplash.orangepi ${consoleargs}"; fi

setenv bootargs "mtdparts=${mtdparts} root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} ubootpart=${partuuid} clk_ignore_unused swiotlb=65536 workqueue.default_affinity_scope=system usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1"; fi

load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}uInitrd
load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}Image

load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
fdt addr ${fdt_addr_r}
fdt rm /soc/lcd_backlight phandle
fdt resize 65536
for overlay_file in ${overlays}; do
	if load ${devtype} ${devnum} ${load_addr} ${prefix}dtb/ky/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
for overlay_file in ${user_overlays}; do
	if load ${devtype} ${devnum} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
		echo "Applying user provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done

booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}

# Recompile with:
# mkimage -C none -A riscv -T script -d /boot/boot.cmd /boot/boot.scr
