#!/usr/bin/perl -w

# Generate usys.S — x86_64 syscall stubs for xv6 userlib programs.
#
# Linux x86-64 syscall calling convention:
#   Syscall number : rax
#   Arguments      : rdi, rsi, rdx, r10, r8, r9  (up to 6)
#   Return value   : rax
#   Preserved      : rdi, rsi, rdx, r10, r8, r9, rbx, rbp, r12–r15
#   Clobbered      : rcx, r11  ("transaction registers")
#
# The SYSCALL instruction itself overwrites rcx (with user RIP) and
# r11 (with user RFLAGS).  These registers are NOT preserved across
# the call — callers must save them beforehand if needed.
#
# C calling convention uses rcx for the 4th argument, so each stub
# copies rcx → r10 before issuing SYSCALL.

print "# generated by usys_x86_64.pl - do not edit\n";
print "#include \"kernel/inc/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " movq %rcx, %r10\n";       # 4th C arg (rcx) -> r10 (SYSCALL clobbers rcx)
    print " movq \$SYS_${name}, %rax\n";
    print " syscall\n";
    print " ret\n";
}

entry("clone");
entry("vfork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("readv");
entry("writev");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("stat");
entry("lstat");
entry("readlink");
entry("link");
entry("symlink");
entry("mkdir");
entry("chdir");
entry("dup");
entry("dup2");
entry("lseek");
entry("poll");
entry("fcntl");
entry("access");
entry("rename");
entry("ftruncate");
entry("getpid");
entry("getppid");
entry("gettid");
entry("getuid");
entry("geteuid");
entry("getrandom");
entry("exit_group");
entry("tgkill");
entry("tkill");
entry("sbrk");
entry("sleep");
entry("nanosleep");
entry("uptime");
entry("gettimeofday");
entry("waitpid");
entry("uname");
entry("sigaction");
entry("sigalarm");
entry("sigreturn");
entry("sigpending");
entry("sigprocmask");
entry("sigsuspend");
entry("sigwait");
entry("pause");

# Memory mapping syscalls
entry("mmap");
entry("munmap");
entry("mprotect");
entry("mremap");
entry("msync");
entry("mincore");
entry("madvise");

entry("getdents");
entry("chroot");
entry("mount");
entry("umount");
entry("getcwd");

entry("memstat");
entry("dumpproc");
entry("dumpchan");
entry("dumppcache");
entry("dumprq");
entry("kernbase");
entry("dumpinode");
entry("dumpblk");
entry("losetup");

entry("ioctl");
entry("tcgetattr");
entry("tcsetattr");

# Process group / session
entry("setpgid");
entry("getpgid");
entry("setsid");
entry("getsid");

entry("sync");

entry("kstats");

# kqueue syscalls
entry("kqueue");
entry("kevent_register");
entry("kevent_wait");

entry("netconf");
