#!/usr/bin/perl -w

# Generate usys.S — x86_64 syscall stubs for xv6 userlib programs.
# Uses SYSCALL instruction with Linux x86_64 ABI:
#   rax = syscall number
#   args: rdi, rsi, rdx, r10, r8, r9
#   return in rax
# Note: userlib stubs use the C calling convention (rdi,rsi,rdx,rcx,r8,r9)
# and must move rcx→r10 because SYSCALL clobbers rcx.

print "# generated by usys_x86_64.pl - do not edit\n";
print "#include \"kernel/inc/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " movq %rcx, %r10\n";       # SYSCALL clobbers rcx; 4th arg goes in r10
    print " movq \$SYS_${name}, %rax\n";
    print " syscall\n";
    print " ret\n";
}

entry("clone");
entry("vfork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("stat");
entry("lstat");
entry("readlink");
entry("link");
entry("symlink");
entry("mkdir");
entry("chdir");
entry("dup");
entry("dup2");
entry("lseek");
entry("poll");
entry("fcntl");
entry("access");
entry("rename");
entry("ftruncate");
entry("getpid");
entry("getppid");
entry("gettid");
entry("getrandom");
entry("exit_group");
entry("tgkill");
entry("tkill");
entry("sbrk");
entry("sleep");
entry("nanosleep");
entry("uptime");
entry("gettimeofday");
entry("waitpid");
entry("uname");
entry("sigaction");
entry("sigalarm");
entry("sigreturn");
entry("sigpending");
entry("sigprocmask");
entry("sigsuspend");
entry("sigwait");
entry("pause");

# Memory mapping syscalls
entry("mmap");
entry("munmap");
entry("mprotect");
entry("mremap");
entry("msync");
entry("mincore");
entry("madvise");

entry("getdents");
entry("chroot");
entry("mount");
entry("umount");
entry("getcwd");

entry("memstat");
entry("dumpproc");
entry("dumpchan");
entry("dumppcache");
entry("dumprq");
entry("kernbase");
entry("dumpinode");

entry("ioctl");
entry("tcgetattr");
entry("tcsetattr");

# Process group / session
entry("setpgid");
entry("getpgid");
entry("setsid");
entry("getsid");

entry("sync");

# kqueue syscalls
entry("kqueue");
entry("kevent_register");
entry("kevent_wait");
