#!/bin/bash
# Build NumPy for xv6 using meson cross-compilation.
#
# Usage:
#   build_numpy.sh <numpy_src> <numpy_build> <sysroot> <arch> \
#                  <cpython_build> <cpython_src> <workspace_root>
#
# The script:
#   1. Discovers the cross-toolchain (gcc, g++, ar, strip, cython)
#   2. Generates a meson cross-file with xv6/musl-specific settings
#   3. Sets _PYTHON_SYSCONFIGDATA_NAME so meson's python module reads
#      the cross-compiled CPython's sysconfig instead of the host's
#   4. Runs meson setup / compile / install
#
# Requirements:
#   - Cross-toolchain with C++ support (riscv64/x86_64-xv6-linux-musl-g++)
#   - Host python3 with meson >= 1.2.99, ninja, cython >= 3.0.6
#   - CPython development headers installed in sysroot (Python.h)
#   - OpenBLAS installed in sysroot (optional, falls back to internal BLAS)

set -euo pipefail

NUMPY_SRC="${1:?Usage: $0 <numpy_src> <numpy_build> <sysroot> <arch> <cpython_build> <cpython_src> <workspace_root>}"
NUMPY_BUILD="${2:?}"
SYSROOT="${3:?}"
ARCH="${4:?}"
CPYTHON_BUILD="${5:?}"
CPYTHON_SRC="${6:?}"
WORKSPACE="${7:?}"

echo "build_numpy: arch=${ARCH} sysroot=${SYSROOT}"

# ── Toolchain detection ──────────────────────────────────────────────────────
case "${ARCH}" in
    x86_64)
        TRIPLET="x86_64-xv6-linux-musl"
        CPU_FAMILY="x86_64"
        DYNAMIC_LINKER="/lib/ld-musl-x86_64.so.1"
        HOST_TRIPLE="x86_64-linux-gnu"
        ARCH_CFLAGS=""
        LONGDOUBLE_FORMAT="INTEL_EXTENDED_16_BYTES_LE"
        ;;
    *)
        TRIPLET="riscv64-xv6-linux-musl"
        CPU_FAMILY="riscv64"
        DYNAMIC_LINKER="/lib/ld-musl-riscv64.so.1"
        HOST_TRIPLE="riscv64-linux-gnu"
        ARCH_CFLAGS="-march=rv64gc -mabi=lp64d -mcmodel=medany"
        LONGDOUBLE_FORMAT="IEEE_QUAD_LE"
        ;;
esac

# Search for cross-compiler in known locations
TOOL_DIR=""
for candidate in \
    "${WORKSPACE}/toolchain/${ARCH}/phase2/bin" \
    "${WORKSPACE}/toolchain/${ARCH}64/phase2/bin" \
    "${WORKSPACE}/toolchain/${ARCH}/bin" \
    "${WORKSPACE}/toolchain/${ARCH}64/bin"; do
    if [ -x "${candidate}/${TRIPLET}-gcc" ]; then
        TOOL_DIR="${candidate}"
        break
    fi
done
if [ -z "${TOOL_DIR}" ]; then
    # Try PATH
    if command -v "${TRIPLET}-gcc" >/dev/null 2>&1; then
        TOOL_DIR="$(dirname "$(command -v "${TRIPLET}-gcc")")"
    else
        echo "build_numpy: ERROR: cross-compiler ${TRIPLET}-gcc not found" >&2
        exit 1
    fi
fi

CC="${TOOL_DIR}/${TRIPLET}-gcc"
CXX="${TOOL_DIR}/${TRIPLET}-g++"
AR="${TOOL_DIR}/${TRIPLET}-ar"
STRIP="${TOOL_DIR}/${TRIPLET}-strip"

if [ ! -x "${CXX}" ]; then
    echo "build_numpy: ERROR: C++ cross-compiler not found: ${CXX}" >&2
    echo "  Rebuild the toolchain with C++ support:" >&2
    echo "    scripts/build_gcc_toolchain.sh --arch=${ARCH}" >&2
    exit 1
fi
echo "build_numpy: CC=${CC}"
echo "build_numpy: CXX=${CXX}"

# GCC internal include directory (stddef.h, stdarg.h, …)
GCC_INCLUDE=$("${CC}" -print-file-name=include)

# ── Cython ────────────────────────────────────────────────────────────────────
CYTHON="$(command -v cython3 2>/dev/null || command -v cython 2>/dev/null || true)"
if [ -z "${CYTHON}" ]; then
    echo "build_numpy: ERROR: cython not found on PATH" >&2
    exit 1
fi
echo "build_numpy: CYTHON=${CYTHON}"

# ── _sysconfigdata for cross-Python ──────────────────────────────────────────
SYSCONFIGDATA_NAME="_sysconfigdata__xv6_${HOST_TRIPLE}"
SYSCONFIGDATA_DIR="${CPYTHON_BUILD}/build/lib.xv6-${CPU_FAMILY}-3.12"
if [ ! -f "${SYSCONFIGDATA_DIR}/${SYSCONFIGDATA_NAME}.py" ]; then
    echo "build_numpy: ERROR: _sysconfigdata not found:" >&2
    echo "  ${SYSCONFIGDATA_DIR}/${SYSCONFIGDATA_NAME}.py" >&2
    exit 1
fi

# ── pkg-config wrapper ───────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PKG_CONFIG="${SCRIPT_DIR}/xv6-pkg-config.sh"
if [ ! -x "${PKG_CONFIG}" ]; then
    echo "build_numpy: WARNING: ${PKG_CONFIG} not found, using false" >&2
    PKG_CONFIG="false"
fi

# ── Compat include directory ─────────────────────────────────────────────────
COMPAT_DIR="${WORKSPACE}/user/musl-xv6/compat"

# ── Generate meson cross-file ────────────────────────────────────────────────
# Place cross-file OUTSIDE the build dir so --wipe doesn't delete it
CROSS_FILE="${NUMPY_BUILD}/../xv6-cross.ini"
mkdir -p "${NUMPY_BUILD}"

cat > "${CROSS_FILE}" <<CROSS_EOF
# Auto-generated by build_numpy.sh — do not edit manually.

[host_machine]
system     = 'linux'
cpu_family = '${CPU_FAMILY}'
cpu        = '${CPU_FAMILY}'
endian     = 'little'

[binaries]
c          = '${CC}'
cpp        = '${CXX}'
ar         = '${AR}'
strip      = '${STRIP}'
cython     = '${CYTHON}'
pkg-config = '${PKG_CONFIG}'

[built-in options]
c_args      = ['--sysroot=${SYSROOT}', '-O2', '-fPIC', ${ARCH_CFLAGS:+$(printf "'%s', " ${ARCH_CFLAGS})}'-isystem', '${COMPAT_DIR}', '-I${SYSROOT}/include/python3.12d', '-D_POSIX_C_SOURCE=200809L', '-DSSIZE_MAX=__LONG_MAX__']
c_link_args = ['--sysroot=${SYSROOT}', '-L${SYSROOT}/lib', '-Wl,-rpath,/lib', '-Wl,--dynamic-linker=${DYNAMIC_LINKER}']
cpp_args    = ['--sysroot=${SYSROOT}', '-O2', '-fPIC', ${ARCH_CFLAGS:+$(printf "'%s', " ${ARCH_CFLAGS})}'-isystem', '${COMPAT_DIR}', '-I${SYSROOT}/include/python3.12d', '-D_POSIX_C_SOURCE=200809L', '-DSSIZE_MAX=__LONG_MAX__']
cpp_link_args = ['--sysroot=${SYSROOT}', '-L${SYSROOT}/lib', '-Wl,-rpath,/lib', '-Wl,--dynamic-linker=${DYNAMIC_LINKER}']
python.install_env  = 'prefix'
python.platlibdir   = 'lib/python3.12/site-packages'
python.purelibdir   = 'lib/python3.12/site-packages'

[properties]
needs_exe_wrapper   = true
sys_root            = '${SYSROOT}'
sizeof_long_double  = 16
longdouble_format   = '${LONGDOUBLE_FORMAT}'
CROSS_EOF

echo "build_numpy: generated cross-file at ${CROSS_FILE}"

# ── Determine BLAS option ────────────────────────────────────────────────────
BLAS_OPT="-Dallow-noblas=true"
if [ -f "${SYSROOT}/lib/pkgconfig/openblas.pc" ]; then
    BLAS_OPT="-Dblas=openblas"
    echo "build_numpy: using OpenBLAS from sysroot"
else
    echo "build_numpy: WARNING: OpenBLAS not found, building with internal fallback"
fi

# ── Meson (prefer NumPy's vendored meson with 'features' module) ──────────────
VENDORED_MESON="${NUMPY_SRC}/vendored-meson/meson/meson.py"
if [ -f "${VENDORED_MESON}" ]; then
    MESON="python3 ${VENDORED_MESON}"
    echo "build_numpy: using vendored meson: ${VENDORED_MESON}"
else
    MESON="meson"
    echo "build_numpy: using system meson (vendored not found)"
fi

# ── Environment ──────────────────────────────────────────────────────────────
export _PYTHON_SYSCONFIGDATA_NAME="${SYSCONFIGDATA_NAME}"
export PYTHONPATH="${SYSCONFIGDATA_DIR}:${PYTHONPATH:-}"
export XV6_SYSROOT="${SYSROOT}"

# ── Meson setup ──────────────────────────────────────────────────────────────
# Wipe previous build if cross-file or source changed
if [ -f "${NUMPY_BUILD}/build.ninja" ]; then
    echo "build_numpy: reconfiguring existing build …"
    ${MESON} setup "${NUMPY_BUILD}" "${NUMPY_SRC}" \
        --cross-file="${CROSS_FILE}" \
        --prefix=/ \
        --wipe \
        "${BLAS_OPT}" \
        -Dlapack=none \
        -Dallow-noblas=true \
        -Ddisable-optimization=true \
        -Ddisable-highway=true \
        -Ddisable-intel-sort=true \
        -Ddisable-threading=true \
        -Dcpu-baseline=none \
        -Dcpu-dispatch=none
else
    echo "build_numpy: configuring fresh build …"
    ${MESON} setup "${NUMPY_BUILD}" "${NUMPY_SRC}" \
        --cross-file="${CROSS_FILE}" \
        --prefix=/ \
        "${BLAS_OPT}" \
        -Dlapack=none \
        -Dallow-noblas=true \
        -Ddisable-optimization=true \
        -Ddisable-highway=true \
        -Ddisable-intel-sort=true \
        -Ddisable-threading=true \
        -Dcpu-baseline=none \
        -Dcpu-dispatch=none
fi

# ── Compile ──────────────────────────────────────────────────────────────────
echo "build_numpy: compiling …"
${MESON} compile -C "${NUMPY_BUILD}" -j16

# ── Install into sysroot ─────────────────────────────────────────────────────
echo "build_numpy: installing into sysroot …"
DESTDIR="${SYSROOT}" ${MESON} install -C "${NUMPY_BUILD}" --no-rebuild

echo "build_numpy: done"
