#!/usr/bin/env python3
"""
Estimate kernel symbol / index sizes from DWARF debug info.

This module provides reusable functions for counting DWARF decoded-line
entries and estimating the sizes of:
  - .ksymbols  : the text-based symbol data generated by gen_addrline.sh
  - .ksymbols_idx : the BSS region for __ksymbols_t rb-tree nodes at runtime

CLI usage:
    estimate_symbol_size.py <objdump> <kernel.o> [--mode ksymbols|ksymbols-idx] [--margin N]

    --mode ksymbols      Estimate .ksymbols text section size (default)
    --mode ksymbols-idx  Estimate .ksymbols_idx BSS size (rb-tree nodes)
    --margin N           Safety margin percentage (default: 20 for ksymbols, 25 for idx)

Output:
    Prints the estimated size in bytes (page-aligned) to stdout.
    Diagnostic info goes to stderr.
"""

import sys
import os
import subprocess
import argparse

# ==============================================================================
# Constants
# ==============================================================================
PAGE_SIZE = 4096

# sizeof(__ksymbols_t) on rv64 with alignment (see kernel/backtrace.c):
#   struct rb_node rb;    // 24 (3 pointers)
#   void *start_addr;     // 8
#   uint32 line;          // 4 + 4 padding
#   const char *symbol;   // 8
#   uint16 symbol_len;    // 2 + 6 padding
#   const char *filename; // 8
#   uint16 filename_len;  // 2 + 6 padding
SIZEOF_KSYMBOLS_T = 80

# Averages for .ksymbols text format produced by gen_addrline.sh
AVG_FILE_HEADER = 60    # path + colon + newline
AVG_SYMBOL_HEADER = 40  # colon + name + newline
AVG_ADDRESS_LINE = 45   # "0123456789abcdef 0123456789abcdef 12345\n"


# ==============================================================================
# Reusable functions (importable by other scripts)
# ==============================================================================

def count_dwarf_entries(objdump: str, elf_path: str) -> tuple:
    """Count address entries and unique files in DWARF decoded line info.

    The output format from ``objdump --dwarf=decodedline`` is a table::

        File name     Line number    Starting address    View    Stmt
        start.c                42          0x80200040               x

    We count every line containing a ``0x`` address in the Starting
    address column.

    Returns:
        (address_line_count, unique_file_set)
    """
    if not os.path.exists(elf_path):
        raise FileNotFoundError(f"ELF not found: {elf_path}")

    try:
        result = subprocess.run(
            [objdump, '--dwarf=decodedline', elf_path],
            capture_output=True, text=True, timeout=300,
        )
    except subprocess.TimeoutExpired:
        raise RuntimeError("objdump timed out")
    except FileNotFoundError:
        raise FileNotFoundError(f"objdump not found: {objdump}")

    if result.returncode != 0:
        raise RuntimeError(f"objdump failed: {result.stderr}")

    files = set()
    address_lines = 0

    for line in result.stdout.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        # CU header lines end with ':' (e.g. "foo.c:")
        if stripped.endswith(':') and '0x' not in stripped:
            files.add(stripped[:-1])
            continue
        # Address entry — any table row containing a hex address
        if '0x' in line:
            address_lines += 1

    return address_lines, files


def page_align(size: int) -> int:
    """Round *size* up to the next 4 KiB page boundary."""
    return ((size + PAGE_SIZE - 1) // PAGE_SIZE) * PAGE_SIZE


def estimate_ksymbols_size(address_lines: int, n_files: int,
                           margin_percent: int = 20) -> int:
    """Estimate .ksymbols text section size (gen_addrline.sh output).

    Returns a page-aligned byte count.
    """
    estimated_symbols = n_files  # rough: one symbol header per file
    base = (n_files * AVG_FILE_HEADER +
            estimated_symbols * AVG_SYMBOL_HEADER +
            address_lines * AVG_ADDRESS_LINE)
    return page_align(int(base * (1 + margin_percent / 100)))


def estimate_ksymbols_idx_size(address_lines: int,
                               margin_percent: int = 25) -> int:
    """Estimate .ksymbols_idx BSS size (rb-tree nodes).

    Each DWARF line entry becomes one ``__ksymbols_t`` at runtime.
    Returns a page-aligned byte count.
    """
    raw = int(address_lines * SIZEOF_KSYMBOLS_T * (1 + margin_percent / 100))
    return page_align(raw)


# ==============================================================================
# CLI
# ==============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Estimate kernel symbol / index sizes from DWARF info.")
    parser.add_argument("objdump", help="Path to objdump binary")
    parser.add_argument("kernel", help="Kernel ELF or relocatable object")
    parser.add_argument("--mode", choices=["ksymbols", "ksymbols-idx"],
                        default="ksymbols",
                        help="Which section size to estimate (default: ksymbols)")
    parser.add_argument("--margin", type=int, default=None,
                        help="Safety margin %% (default: 20 for ksymbols, 25 for idx)")
    args = parser.parse_args()

    try:
        address_lines, files = count_dwarf_entries(args.objdump, args.kernel)
    except (FileNotFoundError, RuntimeError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    if args.mode == "ksymbols":
        margin = args.margin if args.margin is not None else 20
        size = estimate_ksymbols_size(address_lines, len(files), margin)
    else:  # ksymbols-idx
        margin = args.margin if args.margin is not None else 25
        size = estimate_ksymbols_idx_size(address_lines, margin)

    # Estimated size to stdout (for consumption by CMake / scripts)
    print(size)

    # Diagnostics to stderr
    print(f"estimate_symbol_size [{args.mode}]: "
          f"files={len(files)}, address_lines={address_lines}, "
          f"margin={margin}%, size={size} (0x{size:x})",
          file=sys.stderr)


if __name__ == '__main__':
    main()
