#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/inc/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

entry("clone");
entry("vfork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("readv");
entry("writev");
entry("preadv");
entry("pwritev2");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("stat");
entry("lstat");
entry("readlink");
entry("link");
entry("symlink");
entry("mkdir");
entry("chdir");
entry("dup");
entry("dup2");
entry("lseek");
entry("poll");
entry("fcntl");
entry("access");
entry("rename");
entry("ftruncate");
entry("fchmodat");
entry("getpid");
entry("getppid");
entry("gettid");
entry("getuid");
entry("geteuid");
entry("getrandom");
entry("exit_group");
entry("tgkill");
entry("tkill");
entry("sbrk");
entry("sleep");
entry("nanosleep");
entry("uptime");
entry("gettimeofday");
entry("waitpid");
entry("uname");
entry("sigaction");
entry("sigalarm");
entry("sigreturn");
entry("sigpending");
entry("sigprocmask");
entry("sigsuspend");
entry("sigwait");
entry("pause");

# Memory mapping syscalls
entry("mmap");
entry("munmap");
entry("mprotect");
entry("mremap");
entry("msync");
entry("mincore");
entry("madvise");

entry("getdents");
entry("chroot");
entry("mount");
entry("umount");
entry("getcwd");

entry("memstat");
entry("dumpproc");
entry("dumpchan");
entry("dumppcache");
entry("dumprq");
entry("kernbase");
entry("dumpinode", 1);
entry("dumpblk");
entry("losetup");

entry("ioctl");
entry("tcgetattr");
entry("tcsetattr");

# Process group / session
entry("setpgid");
entry("getpgid");
entry("setsid");
entry("getsid");

entry("sync");

entry("kstats");

# kqueue syscalls
entry("kqueue");
entry("kevent_register");
entry("kevent_wait");

entry("netconf");
