#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/inc/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

# Entry with custom syscall name (for aliasing old names to new syscalls)
sub entry_aliased {
    my ($name, $syscall) = @_;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${syscall}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("clone");
entry("exit");
entry("wait");
# Use VFS syscalls for file operations
entry_aliased("pipe", "vfs_pipe");
entry_aliased("read", "vfs_read");
entry_aliased("write", "vfs_write");
entry_aliased("close", "vfs_close");
entry("kill");
entry("exec");
entry_aliased("open", "vfs_open");
entry("mknod");
entry_aliased("unlink", "vfs_unlink");
entry_aliased("fstat", "vfs_fstat");
entry_aliased("link", "vfs_link");
entry_aliased("symlink", "vfs_symlink");
entry_aliased("mkdir", "vfs_mkdir");
entry_aliased("chdir", "vfs_chdir");
entry_aliased("dup", "vfs_dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("sigaction");
entry("sigalarm");
entry("sigreturn");
entry("sigpending");
entry("sigprocmask");
entry("pause");

# New VFS-specific syscalls
entry("getdents");
entry("chroot");
entry("mount");
entry("umount");
entry("getcwd");

entry("memstat");
entry("dumpproc");
entry("dumpchan");
entry("dumppcache");
entry("dumprq");
entry("kernbase");
entry("dumpinode", 1);

entry("sync");
