#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/inc/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

entry("clone");
entry("vfork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("symlink");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("gettid");
entry("exit_group");
entry("tgkill");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("sigaction");
entry("sigalarm");
entry("sigreturn");
entry("sigpending");
entry("sigprocmask");
entry("pause");

# Memory mapping syscalls
entry("mmap");
entry("munmap");
entry("mprotect");
entry("mremap");
entry("msync");
entry("mincore");
entry("madvise");

entry("getdents");
entry("chroot");
entry("mount");
entry("umount");
entry("getcwd");

entry("memstat");
entry("dumpproc");
entry("dumpchan");
entry("dumppcache");
entry("dumprq");
entry("kernbase");
entry("dumpinode", 1);

entry("sync");
